ProjectManagement/ProjectManagement/faqs/urls.py
from django.urls import path

from ProjectManagement.faqs.views import faqs_page_view, leave_requests_page_view, other_requests_page_view, \
    annual_statement_page_view

urlpatterns = (
    path('', faqs_page_view, name='faqs-page'),
    path('leave_request/', leave_requests_page_view, name='leave-requests-page'),
    path('other_request/', other_requests_page_view, name='other-requests-page'),
    path('annual_statement/', annual_statement_page_view, name='annual-statement-page'),
)

ProjectManagement/ProjectManagement/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ProjectManagement.projects.urls')),
    path('accounts/', include('ProjectManagement.accounts.urls')),
    path('faqs/', include('ProjectManagement.faqs.urls')),
    path('apis/', include('ProjectManagement.apis.urls')),
]

ProjectManagement/ProjectManagement/faqs/models.py
from django.db import models

from django.core.exceptions import ValidationError




class LeaveApplication(models.Model):
    CHOICES = (
        ('SICK_LEAVE', 'Sick Leave'),
        ('PAID_LEAVE', 'Paid Leave'),
        ('UNPAID_LEAVE', 'Unpaid Leave'),
    )

    CHOICES_STATUS = (
        ('PENDING', 'Pending'),
        ('CONFIRMED', 'Confirmed'),
        ('DECLINED', 'Declined'),
    )

    worker = models.ForeignKey('accounts.WorkerUser', on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)
    reason = models.TextField(max_length=300, blank=False, null=False)
    start_date = models.DateField(blank=False, null=False)
    end_date = models.DateField(blank=False, null=False)
    days_requested = models.PositiveIntegerField(blank=True, null=True)
    leave_type = models.CharField(max_length=30, choices=CHOICES, default='UNPAID_LEAVE', blank=False, null=False)
    status = models.CharField(max_length=30, choices=CHOICES_STATUS, default='PENDING', blank=False, null=False)

    def save(self, *args, **kwargs):
        if self.start_date > self.end_date:
            raise ValidationError('Start date must be before end date!')

        self.days_requested = (self.end_date - self.start_date).days + 1

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.worker.get_full_name()} requests {self.days_requested} days of {self.leave_type}'


class OtherApplication(models.Model):
    worker = models.ForeignKey('accounts.WorkerUser', on_delete=models.SET_NULL, null=True)
    request_type = models.CharField(max_length=30, blank=False, null=False)
    request_description = models.TextField(max_length=300, blank=False, null=False)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return f'{self.worker.get_full_name()} requests {self.request_type}'

ProjectManagement/ProjectManagement/faqs/forms.py
from django import forms

from ProjectManagement.faqs.models import LeaveApplication, OtherApplication


class LeaveApplicationForm(forms.ModelForm):
    class Meta:
        model = LeaveApplication
        fields = {'reason', 'start_date', 'end_date', 'leave_type'}


class OtherApplicationForm(forms.ModelForm):
    class Meta:
        model = OtherApplication
        fields = {'request_type', 'request_description'}

ProjectManagement/ProjectManagement/faqs/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from ProjectManagement.faqs.forms import LeaveApplicationForm, OtherApplicationForm


@login_required
def faqs_page_view(request):
    return render(request, 'faqs/faqs-page.html')


@login_required
def leave_requests_page_view(request):
    worker = request.user
    if request.method == 'POST':
        form = LeaveApplicationForm(request.POST)
        if form.is_valid():
            leave = form.save(commit=False)
            leave.worker = worker
            leave.save()
            return redirect('faqs-page')
    else:
        form = LeaveApplicationForm()

    context = {
        'form': form,
        'worker': worker,
    }

    return render(request, 'faqs/faqs-leave-requests-page.html', context)


@login_required
def other_requests_page_view(request):
    worker = request.user
    if request.method == 'POST':
        form = OtherApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.worker = worker
            application.save()
            return redirect('projects-landing-page')
    else:
        form = OtherApplicationForm()

    context = {
        'worker': worker,
        'form': form,
    }

    return render(request, 'faqs/faqs-other-requests-page.html', context)


@login_required
def annual_statement_page_view(request):
    worker = request.user
    context = {
        'worker': worker,
    }
    return render(request, 'faqs/faqs-annual-statement-page.html', context)

ProjectManagement/templates/faqs/faqs-annual-statement-page.html
{% extends 'base.html' %}
{% block content %}
    <p class="lead" style="margin-left: 74px;">This is a list of all your leave requests</p>
    <table class="table table-striped" style="margin: 10px auto;
                max-width: 90%;">
        <thead>
        <tr>
            <th scope="col">Leave Type</th>
            <th scope="col">Days</th>
            <th scope="col">Date</th>
            <th scope="col">Start</th>
            <th scope="col">End</th>
            <th scope="col">Status</th>

        </tr>
        </thead>
        <tbody>
        {% for request in worker.get_leave_all %}
            <tr>
                <td>{{ request.get_leave_type_display }}</td>
                <td>{{ request.days_requested }}</td>
                <td>{{ request.date }}</td>
                <td>{{ request.start_date }}</td>
                <td>{{ request.end_date }}</td>
                <td>{{ request.status }}</td>

            </tr>
        {% endfor %}
        </tbody>
    </table>
    <p class="lead" style="margin-left: 74px;  margin-top: 50px;">This is a list of your total leave days by category.</p>
    <table class="table table-striped" style="margin: 10px auto;
    max-width: 90%;">
        <thead>
        <tr>
            <th scope="col">Leave Type</th>
            <th scope="col">Days</th>
        </tr>
        </thead>
        <tbody>
        {% for key, value in worker.get_leave.items %}
            <tr>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}

ProjectManagement/templates/faqs/faqs-leave-requests-page.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <form style="max-width: 330px; padding: 1rem; margin: auto;" method="post">
        <h1 class="h3 mb-3 fw-normal">Leave Request</h1>
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.reason.id }}" class="form-label">Reason</label>
            {% render_field form.reason class='form-control' %}
        </div>
        <div class="mb-3">
            <label for="id_start_date" class="form-label">Start Date</label>
            {% render_field form.start_date class='form-control' type='date' %}
        </div>
        <div class="mb-3">
            <label for="id_end_date" class="form-label">End Date</label>
            {% render_field form.end_date class='form-control' type='date' %}
        </div>
        <div class="mb-3">
            <label for="id_leave_type" class="form-label">Leave Type</label>
            {% render_field form.leave_type class='form-control' type='date' %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

ProjectManagement/templates/faqs/faqs-other-requests-page.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}
    <form style="max-width: 330px; padding: 1rem; margin: auto;" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="{{ form.request_description.id }}" class="form-label">Request Description</label>
            {% render_field form.request_description class='form-control' %}
        </div>
        <div class="mb-3">
            <label for="{{ form.request_type.id }}" class="form-label">Request type</label>
            {% render_field form.request_type class='form-control' %}
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

ProjectManagement/templates/faqs/faqs-page.html
{% extends 'base.html' %}
{% block content %}
    <div class="container px-4 py-5" id="featured-3">
        <h2 class="pb-2 border-bottom">Columns with icons</h2>
        <div class="row g-4 py-5 row-cols-1 row-cols-lg-3">
            <div class="feature col">
                <h3 class="fs-2 text-body-emphasis">Leave Requests</h3>
                <p>Click the link bellow for paid, unpaid or medical leave requests!</p>
                <a href="{% url 'leave-requests-page' %}" class="icon-link">
                    Click Here!
                    <svg class="bi">
                        <use xlink:href="#chevron-right"></use>
                    </svg>
                </a>
            </div>
            <div class="feature col">
                <h3 class="fs-2 text-body-emphasis">Other Requests</h3>
                <p>Click the link bellow for resignation letters, raises and position changes!</p>
                <a href="{% url 'other-requests-page' %}" class="icon-link">
                    Click Here!
                    <svg class="bi">
                        <use xlink:href="#chevron-right"></use>
                    </svg>
                </a>
            </div>
            <div class="feature col">
                <h3 class="fs-2 text-body-emphasis">Yearly Statements</h3>
                <p>Click the link bellow for an annual report of your employment history!</p>
                <a href="{% url 'annual-statement-page' %}" class="icon-link">
                    Click Here!
                    <svg class="bi">
                        <use xlink:href="#chevron-right"></use>
                    </svg>
                </a>
            </div>
        </div>
    </div>
{% endblock %}